version: 2
build:
  os: ubuntu-22.04
  tools:
    python: 'latest'
python:
  install:
    - requirements: requirements/docs.txt
    - method: pip
      path: .
sphinx:
  builder: dirhtml
  fail_on_warning: true
