os: linux
dist: xenial

sudo: false
language: python

matrix:
  fast_finish: true
  include:
    - python: 3.10
      env: FLASK_ENV=TESTING PRAGMA_VERSION=py3.10
    - python: 3.9
      env: FLASK_ENV=TESTING PRAGMA_VERSION=py3.9
    - python: 3.8
      env: FLASK_ENV=TESTING PRAGMA_VERSION=py3.8
    - python: 3.7
      env: FLASK_ENV=TESTING PRAGMA_VERSION=py3.7
    - python: 3.6
      env: FLASK_ENV=TESTING PRAGMA_VERSION=py3.6

install:
  - pip install --upgrade pip setuptools --quiet
  - pip install -r requirements/base.txt --quiet
  - pip install -r requirements/test.txt --quiet
  - pip install -r requirements/ci.txt --quiet

script:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.10' ]]; then mypy --install-types --non-interactive src/; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.10' ]]; then pytype; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.10' ]]; then bandit -r src/; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.10' ]]; then safety check; fi
  - flake8 src/ tests/
  - pylint src/ tests/
  - py.test

after_success:
  - coveralls
