FROM python:3.8-alpine

ENV PYTHONUNBUFFERED=1 \
    PRAGMA_VERSION=py3.8 \
    DEBUG=0

WORKDIR /code

COPY requirements/ /code/requirements/

RUN set -ex \
    && apk add --no-cache --virtual .build-deps \
        gcc \
        musl-dev \
        python3-dev \
    && pip install pip setuptools wheel --upgrade \
    && pip install -r requirements/base.txt \
    && pip install -r requirements/test.txt \
    && pip install -r requirements/ci.txt \
    && apk del .build-deps \
    && addgroup -S kuchulu \
    && adduser \
        --disabled-password \
        --gecos "" \
        --ingroup kuchulu \
        --no-create-home \
        -s /bin/false \
        kuchulu

ARG VERSION=1
RUN echo "Vesion: ${VERSION}"

COPY . /code/

RUN chown kuchulu:kuchulu -R /code

USER kuchulu
